export default [
  {
    "login": "faraazahmad",
    "id": 19265077,
    "node_id": "MDQ6VXNlcjE5MjY1MDc3",
    "avatar_url": "https://avatars.githubusercontent.com/u/19265077?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/faraazahmad",
    "html_url": "https://github.com/faraazahmad",
    "followers_url": "https://api.github.com/users/faraazahmad/followers",
    "following_url": "https://api.github.com/users/faraazahmad/following{/other_user}",
    "gists_url": "https://api.github.com/users/faraazahmad/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/faraazahmad/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/faraazahmad/subscriptions",
    "organizations_url": "https://api.github.com/users/faraazahmad/orgs",
    "repos_url": "https://api.github.com/users/faraazahmad/repos",
    "events_url": "https://api.github.com/users/faraazahmad/events{/privacy}",
    "received_events_url": "https://api.github.com/users/faraazahmad/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Arshilgenius",
    "id": 21264401,
    "node_id": "MDQ6VXNlcjIxMjY0NDAx",
    "avatar_url": "https://avatars.githubusercontent.com/u/21264401?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Arshilgenius",
    "html_url": "https://github.com/Arshilgenius",
    "followers_url": "https://api.github.com/users/Arshilgenius/followers",
    "following_url": "https://api.github.com/users/Arshilgenius/following{/other_user}",
    "gists_url": "https://api.github.com/users/Arshilgenius/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Arshilgenius/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Arshilgenius/subscriptions",
    "organizations_url": "https://api.github.com/users/Arshilgenius/orgs",
    "repos_url": "https://api.github.com/users/Arshilgenius/repos",
    "events_url": "https://api.github.com/users/Arshilgenius/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Arshilgenius/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "zainthecoder",
    "id": 23193284,
    "node_id": "MDQ6VXNlcjIzMTkzMjg0",
    "avatar_url": "https://avatars.githubusercontent.com/u/23193284?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zainthecoder",
    "html_url": "https://github.com/zainthecoder",
    "followers_url": "https://api.github.com/users/zainthecoder/followers",
    "following_url": "https://api.github.com/users/zainthecoder/following{/other_user}",
    "gists_url": "https://api.github.com/users/zainthecoder/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zainthecoder/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zainthecoder/subscriptions",
    "organizations_url": "https://api.github.com/users/zainthecoder/orgs",
    "repos_url": "https://api.github.com/users/zainthecoder/repos",
    "events_url": "https://api.github.com/users/zainthecoder/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zainthecoder/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "areeshaf",
    "id": 34888145,
    "node_id": "MDQ6VXNlcjM0ODg4MTQ1",
    "avatar_url": "https://avatars.githubusercontent.com/u/34888145?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/areeshaf",
    "html_url": "https://github.com/areeshaf",
    "followers_url": "https://api.github.com/users/areeshaf/followers",
    "following_url": "https://api.github.com/users/areeshaf/following{/other_user}",
    "gists_url": "https://api.github.com/users/areeshaf/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/areeshaf/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/areeshaf/subscriptions",
    "organizations_url": "https://api.github.com/users/areeshaf/orgs",
    "repos_url": "https://api.github.com/users/areeshaf/repos",
    "events_url": "https://api.github.com/users/areeshaf/events{/privacy}",
    "received_events_url": "https://api.github.com/users/areeshaf/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "anmolmalik97",
    "id": 35213067,
    "node_id": "MDQ6VXNlcjM1MjEzMDY3",
    "avatar_url": "https://avatars.githubusercontent.com/u/35213067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/anmolmalik97",
    "html_url": "https://github.com/anmolmalik97",
    "followers_url": "https://api.github.com/users/anmolmalik97/followers",
    "following_url": "https://api.github.com/users/anmolmalik97/following{/other_user}",
    "gists_url": "https://api.github.com/users/anmolmalik97/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/anmolmalik97/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/anmolmalik97/subscriptions",
    "organizations_url": "https://api.github.com/users/anmolmalik97/orgs",
    "repos_url": "https://api.github.com/users/anmolmalik97/repos",
    "events_url": "https://api.github.com/users/anmolmalik97/events{/privacy}",
    "received_events_url": "https://api.github.com/users/anmolmalik97/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "anasM0hammad",
    "id": 37591511,
    "node_id": "MDQ6VXNlcjM3NTkxNTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/37591511?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/anasM0hammad",
    "html_url": "https://github.com/anasM0hammad",
    "followers_url": "https://api.github.com/users/anasM0hammad/followers",
    "following_url": "https://api.github.com/users/anasM0hammad/following{/other_user}",
    "gists_url": "https://api.github.com/users/anasM0hammad/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/anasM0hammad/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/anasM0hammad/subscriptions",
    "organizations_url": "https://api.github.com/users/anasM0hammad/orgs",
    "repos_url": "https://api.github.com/users/anasM0hammad/repos",
    "events_url": "https://api.github.com/users/anasM0hammad/events{/privacy}",
    "received_events_url": "https://api.github.com/users/anasM0hammad/received_events",
    "type": "User",
    "site_admin": false
  }
]