export default {
  "login": "asheeque",
  "id": 19776365,
  "node_id": "MDQ6VXNlcjE5Nzc2MzY1",
  "avatar_url": "https://avatars.githubusercontent.com/u/19776365?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/asheeque",
  "html_url": "https://github.com/asheeque",
  "followers_url": "https://api.github.com/users/asheeque/followers",
  "following_url": "https://api.github.com/users/asheeque/following{/other_user}",
  "gists_url": "https://api.github.com/users/asheeque/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/asheeque/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/asheeque/subscriptions",
  "organizations_url": "https://api.github.com/users/asheeque/orgs",
  "repos_url": "https://api.github.com/users/asheeque/repos",
  "events_url": "https://api.github.com/users/asheeque/events{/privacy}",
  "received_events_url": "https://api.github.com/users/asheeque/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Asheeque  Chericham Veettil Maliyakkal",
  "company": null,
  "blog": "",
  "location": "New York",
  "email": null,
  "hireable": null,
  "bio": "Graduate student at University at Buffalo",
  "twitter_username": null,
  "public_repos": 14,
  "public_gists": 1,
  "followers": 6,
  "following": 7,
  "created_at": "2016-06-06T10:55:52Z",
  "updated_at": "2023-01-21T16:02:59Z"
}